Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -5,14 +5,58 @@ CACHE_DIR=$2
 
 echo "Cache Dir : ${CACHE_DIR}"
 mkdir -p ${CACHE_DIR}
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
 
-apt-get install python-software-properties
-apt-add-repository "deb http://badgerports.org precise main"
+# fail fast
+set -e
 
-apt-get update
+mktmpdir() {
+  dir=$(mktemp -t mono-XXXX)
+  rm -rf $dir
+  mkdir -p $dir
+  echo $dir
+}
 
-echo "----Install Mono----"
-apt-get -o Dir::Cache=${CACHE_DIR} install mono-complete mono-gmcs mono-gac mono-utils monodevelop monodoc-browser monodevelop-nunit monodevelop-versioncontrol
+# config
+MONO_VERSION="2.10.8"
+S3_BUCKET="bh-buildpack-mono"
+
+# parse and derive params
+BUILD_DIR=$1
+CACHE_DIR=$2
+
+# s3 packages
+MONO_PACKAGE="http://${S3_BUCKET}.s3.amazonaws.com/mono-${MONO_VERSION}.tar.gz"
+
+# vendor directories
+VENDORED_MONO="$(mktmpdir mono)"
+
+# download and unpack packages
+echo "-----> Fetching Mono binaries"
+mkdir -p $VENDORED_MONO && curl $MONO_PACKAGE -s -o - | tar xzf - -C $VENDORED_MONO
+
+# vendor node into the slug
+PATH="$BUILD_DIR/bin:$PATH"
+echo "-----> Vendoring mono $MONO_VERSION"
+mkdir -p "$BUILD_DIR/mono-build"
+mkdir -p "$BUILD_DIR/mono-build/bin/"
+cp -r "$VENDORED_MONO/bin/" "$BUILD_DIR/mono-build/"
+mkdir -p "$BUILD_DIR/mono-build/etc/"
+cp -r "$VENDORED_MONO/etc/" "$BUILD_DIR/mono-build/"
+mkdir -p "$BUILD_DIR/mono-build/include/"
+cp -r "$VENDORED_MONO/include/" "$BUILD_DIR/mono-build/"
+mkdir -p "$BUILD_DIR/mono-build/lib/"
+cp -r "$VENDORED_MONO/lib/" "$BUILD_DIR/mono-build/"
+mkdir -p "$BUILD_DIR/mono-build/share/"
+cp -r "$VENDORED_MONO/share/" "$BUILD_DIR/mono-build/"
+
+# setting up paths for building
+PATH="$BUILD_DIR/mono-build/bin:$VENDORED_MONO/bin:$PATH"
+INCLUDE_PATH="$BUILD_DIR/mono-build/include"
+export CPATH="$INCLUDE_PATH"
+export CPPPATH="$INCLUDE_PATH"
+
 
 echo "----Install XSP----"
 apt-get -o Dir::Cache=${CACHE_DIR} install mono-xsp2 mono-xsp2-base asp.net2-examples
